import { _provider } from './gulp';

let File = require('gulp-util').File;

describe('gulp-generate', () => {
  let fakeGenerate;
  let gulpGenerate;

  beforeEach(() => {
    fakeGenerate = jasmine.createSpy('generate');
    gulpGenerate = _provider.bind(null, fakeGenerate);
  });

  it('should push all the files generated by generate', done => {
    let outName = 'outName';
    let localDataList = [{}];
    let generatedFiles = { file1: 'content1', file2: 'content2' };
    let templateFile = new File({ content: new Buffer('content') });
    fakeGenerate.and.returnValue(generatedFiles);

    let stream = gulpGenerate(outName, localDataList);
    let outputData = [];
    stream.on('data', file => {
      outputData.push(file);
    });
    stream.once('finish', () => {
      expect(fakeGenerate).toHaveBeenCalledWith(templateFile, outName, localDataList, {});
      expect(outputData[0].path).toEqual('file1');
      expect(outputData[0].contents.toString()).toEqual('content1');
      expect(outputData[1].path).toEqual('file2');
      expect(outputData[1].contents.toString()).toEqual('content2');
      done();
    });
    stream.write(templateFile);
    stream.end();
  });
});
